### ISSUE TITLE
Change location of JS script tag in HTML

### ISSUE THREAD

**Issue by rawbirth** [Robarto97/Website#1]
Please read this post:

https://faqs.skillcrush.com/article/176-where-should-js-script-tags-be-linked-in-html-documents

After you have fully understood the concept you can go ahead and adjust the JS script tag accordingly. After finished please close this issue.

**Comment by Robarto97** [comment]
The HTML elements should load first and then the JS files. That's why the <script> tags are put before the closing <body> tag. Got it!

**Comment by rawbirth** [comment]
> The HTML elements should load first and then the JS files. That's why the <script> tags are put before the closing tag. Got it!

Exactly!
